apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-config
  namespace: cinema-exam
data:
  MOVIE_ENVIRONMENT: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-config
  namespace: cinema-exam
data:
  MOVIE_URL: http://movie:8080
