apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-debug
  namespace: cinema-exam
spec:
  replicas: 1
  selector:
    matchLabels: { app: ticket-debug }
  template:
    metadata:
      labels: { app: ticket-debug }
    spec:
      containers:
        - name: ticket
          image: ticket-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: ticket-config
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8080 }
            periodSeconds: 5
